<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.3" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" Version="13.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>72977101-1dad-4ebf-9160-0a1aa2d4232f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Github-Analyzer.WebApi\Github-Analyzer.WebApi.csproj" />
  </ItemGroup>

</Project>
