<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GithubAnalyzer.Worker</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Dapper.AOT</InterceptorsNamespaces>
    <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Dapper.AOT</InterceptorsPreviewNamespaces>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="Dapper.AOT" Version="1.1.0" />
    <PackageReference Include="Aspire.Npgsql" Version="13.4.2" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="13.4.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="TreeSitter.CodeGraph" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Github-Analyzer.Shared\Github-Analyzer.Shared.csproj" />
    <ProjectReference Include="..\Github-Analyzer.ServiceDefaults\Github-Analyzer.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
