/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/components/_layouts/AuthLayout.vue')['default']
    CodeGraphTab: typeof import('./src/components/project-details-tab/CodeGraphTab.vue')['default']
    CodeGraphView: typeof import('./src/components/code-graph/CodeGraphView.vue')['default']
    CodeViewer: typeof import('./src/components/code-viewer/CodeViewer.vue')['default']
    CodeViewerSearch: typeof import('./src/components/code-viewer/CodeViewerSearch.vue')['default']
    CodeViewerSettings: typeof import('./src/components/code-viewer/CodeViewerSettings.vue')['default']
    CodeViewerTabs: typeof import('./src/components/code-viewer/CodeViewerTabs.vue')['default']
    Dashboard: typeof import('./src/components/_layouts/Dashboard.vue')['default']
    GraphContextMenu: typeof import('./src/components/code-graph/GraphContextMenu.vue')['default']
    GraphLegend: typeof import('./src/components/code-graph/GraphLegend.vue')['default']
    GraphSearchModal: typeof import('./src/components/code-graph/GraphSearchModal.vue')['default']
    GraphSettingsMenu: typeof import('./src/components/code-graph/GraphSettingsMenu.vue')['default']
    MainSidebar: typeof import('./src/components/MainSidebar.vue')['default']
    NAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    NApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    NAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    NBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    NButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    NCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    NDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    NForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    NFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    NIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    NInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    NKbd: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    NModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    NPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    NSelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    NSkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    NTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    OnboardingStepTracker: typeof import('./src/components/OnboardingStepTracker.vue')['default']
    OnboardingWrapper: typeof import('./src/components/OnboardingWrapper.vue')['default']
    OverviewTab: typeof import('./src/components/project-details-tab/OverviewTab.vue')['default']
    ProjectItemButton: typeof import('./src/components/ProjectItemButton.vue')['default']
    ProjectVersionSelector: typeof import('./src/components/ProjectVersionSelector.vue')['default']
    ProviderAuthButton: typeof import('./src/components/ProviderAuthButton.vue')['default']
    ProviderAuthSection: typeof import('./src/components/ProviderAuthSection.vue')['default']
    RepositoryReadme: typeof import('./src/components/RepositoryReadme.vue')['default']
    RepositoryStatistics: typeof import('./src/components/RepositoryStatistics.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserProfileCard: typeof import('./src/components/UserProfileCard.vue')['default']
    ZeroMD: typeof import('./src/components/ZeroMD.vue')['default']
  }
}
