/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/components/_layouts/AuthLayout.vue')['default']
    CodeGraphTab: typeof import('./src/components/project-details-tab/CodeGraphTab.vue')['default']
    CodeGraphView: typeof import('./src/components/code-graph/CodeGraphView.vue')['default']
    Dashboard: typeof import('./src/components/_layouts/Dashboard.vue')['default']
    GraphLegend: typeof import('./src/components/code-graph/GraphLegend.vue')['default']
    GraphSearchModal: typeof import('./src/components/code-graph/GraphSearchModal.vue')['default']
    MainSidebar: typeof import('./src/components/MainSidebar.vue')['default']
    NAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    NApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    NAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    NBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    NButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    NCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    NDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    NForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    NFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    NIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    NInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    NKbd: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    NPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    ProjectItemButton: typeof import('./src/components/ProjectItemButton.vue')['default']
    ProjectVersionSelector: typeof import('./src/components/ProjectVersionSelector.vue')['default']
    ProviderAuthButton: typeof import('./src/components/ProviderAuthButton.vue')['default']
    ProviderAuthSection: typeof import('./src/components/ProviderAuthSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticTab: typeof import('./src/components/project-details-tab/StatisticTab.vue')['default']
    UserProfileCard: typeof import('./src/components/UserProfileCard.vue')['default']
  }
}
